version: '3'
services:
    app1:
        build:
            context: .
    
        ports:
            - "3000:3000"
        command: >
            bash -c "gunicorn --bind 0.0.0.0:3000 wsgi1:app"
    app2:
        build:
            context: .
        ports:
            - "5000:5000"
        command: >
            bash -c "gunicorn --bind 0.0.0.0:5000 wsgi2:app"


